-- Manual Team Import SQL
-- Generated: 2025-09-07T06:18:33.339Z
-- Total teams: 96

-- Insert teams with manual data
INSERT INTO teams (
  name, slug, crest_url, competition_id, country_code, 
  external_ref, venue, website, founded_year
) VALUES
  ('Arsenal', 'arsenal', NULL, 1, 'ENG', 'manual_1_1', NULL, NULL, NULL),
  ('Aston Villa', 'aston-villa', NULL, 1, 'ENG', 'manual_1_2', NULL, NULL, NULL),
  ('AFC Bournemouth', 'afc-bournemouth', NULL, 1, 'ENG', 'manual_1_3', NULL, NULL, NULL),
  ('Brentford', 'brentford', NULL, 1, 'ENG', 'manual_1_4', NULL, NULL, NULL),
  ('Brighton & Hove Albion', 'brighton-hove-albion', NULL, 1, 'ENG', 'manual_1_5', NULL, NULL, NULL),
  ('Chelsea', 'chelsea', NULL, 1, 'ENG', 'manual_1_6', NULL, NULL, NULL),
  ('Crystal Palace', 'crystal-palace', NULL, 1, 'ENG', 'manual_1_7', NULL, NULL, NULL),
  ('Everton', 'everton', NULL, 1, 'ENG', 'manual_1_8', NULL, NULL, NULL),
  ('Fulham', 'fulham', NULL, 1, 'ENG', 'manual_1_9', NULL, NULL, NULL),
  ('Ipswich Town', 'ipswich-town', NULL, 1, 'ENG', 'manual_1_10', NULL, NULL, NULL),
  ('Leicester City', 'leicester-city', NULL, 1, 'ENG', 'manual_1_11', NULL, NULL, NULL),
  ('Liverpool', 'liverpool', NULL, 1, 'ENG', 'manual_1_12', NULL, NULL, NULL),
  ('Manchester City', 'manchester-city', NULL, 1, 'ENG', 'manual_1_13', NULL, NULL, NULL),
  ('Manchester United', 'manchester-united', NULL, 1, 'ENG', 'manual_1_14', NULL, NULL, NULL),
  ('Newcastle United', 'newcastle-united', NULL, 1, 'ENG', 'manual_1_15', NULL, NULL, NULL),
  ('Nottingham Forest', 'nottingham-forest', NULL, 1, 'ENG', 'manual_1_16', NULL, NULL, NULL),
  ('Southampton', 'southampton', NULL, 1, 'ENG', 'manual_1_17', NULL, NULL, NULL),
  ('Tottenham Hotspur', 'tottenham-hotspur', NULL, 1, 'ENG', 'manual_1_18', NULL, NULL, NULL),
  ('West Ham United', 'west-ham-united', NULL, 1, 'ENG', 'manual_1_19', NULL, NULL, NULL),
  ('Wolverhampton Wanderers', 'wolverhampton-wanderers', NULL, 1, 'ENG', 'manual_1_20', NULL, NULL, NULL),
  ('FC Augsburg', 'fc-augsburg', NULL, 2, 'GER', 'manual_2_1', NULL, NULL, NULL),
  ('Bayer 04 Leverkusen', 'bayer-leverkusen', NULL, 2, 'GER', 'manual_2_2', NULL, NULL, NULL),
  ('Bayern Munich', 'bayern-munich', NULL, 2, 'GER', 'manual_2_3', NULL, NULL, NULL),
  ('Borussia Dortmund', 'borussia-dortmund', NULL, 2, 'GER', 'manual_2_4', NULL, NULL, NULL),
  ('Borussia Mönchengladbach', 'borussia-monchengladbach', NULL, 2, 'GER', 'manual_2_5', NULL, NULL, NULL),
  ('Eintracht Frankfurt', 'eintracht-frankfurt', NULL, 2, 'GER', 'manual_2_6', NULL, NULL, NULL),
  ('1. FC Heidenheim', '1-fc-heidenheim', NULL, 2, 'GER', 'manual_2_7', NULL, NULL, NULL),
  ('TSG Hoffenheim', 'tsg-hoffenheim', NULL, 2, 'GER', 'manual_2_8', NULL, NULL, NULL),
  ('Holstein Kiel', 'holstein-kiel', NULL, 2, 'GER', 'manual_2_9', NULL, NULL, NULL),
  ('RB Leipzig', 'rb-leipzig', NULL, 2, 'GER', 'manual_2_10', NULL, NULL, NULL),
  ('1. FSV Mainz 05', '1-fsv-mainz-05', NULL, 2, 'GER', 'manual_2_11', NULL, NULL, NULL),
  ('FC St. Pauli', 'fc-st-pauli', NULL, 2, 'GER', 'manual_2_12', NULL, NULL, NULL),
  ('SC Freiburg', 'sc-freiburg', NULL, 2, 'GER', 'manual_2_13', NULL, NULL, NULL),
  ('FC Schalke 04', 'fc-schalke-04', NULL, 2, 'GER', 'manual_2_14', NULL, NULL, NULL),
  ('VfB Stuttgart', 'vfb-stuttgart', NULL, 2, 'GER', 'manual_2_15', NULL, NULL, NULL),
  ('Union Berlin', 'union-berlin', NULL, 2, 'GER', 'manual_2_16', NULL, NULL, NULL),
  ('VfL Bochum', 'vfl-bochum', NULL, 2, 'GER', 'manual_2_17', NULL, NULL, NULL),
  ('Werder Bremen', 'werder-bremen', NULL, 2, 'GER', 'manual_2_18', NULL, NULL, NULL),
  ('Athletic Bilbao', 'athletic-bilbao', NULL, 3, 'ESP', 'manual_3_1', NULL, NULL, NULL),
  ('Atlético Madrid', 'atletico-madrid', NULL, 3, 'ESP', 'manual_3_2', NULL, NULL, NULL),
  ('FC Barcelona', 'fc-barcelona', NULL, 3, 'ESP', 'manual_3_3', NULL, NULL, NULL),
  ('Real Betis', 'real-betis', NULL, 3, 'ESP', 'manual_3_4', NULL, NULL, NULL),
  ('Cádiz CF', 'cadiz-cf', NULL, 3, 'ESP', 'manual_3_5', NULL, NULL, NULL),
  ('Celta Vigo', 'celta-vigo', NULL, 3, 'ESP', 'manual_3_6', NULL, NULL, NULL),
  ('Deportivo Alavés', 'deportivo-alaves', NULL, 3, 'ESP', 'manual_3_7', NULL, NULL, NULL),
  ('Espanyol', 'espanyol', NULL, 3, 'ESP', 'manual_3_8', NULL, NULL, NULL),
  ('Getafe CF', 'getafe-cf', NULL, 3, 'ESP', 'manual_3_9', NULL, NULL, NULL),
  ('Girona FC', 'girona-fc', NULL, 3, 'ESP', 'manual_3_10', NULL, NULL, NULL),
  ('Las Palmas', 'las-palmas', NULL, 3, 'ESP', 'manual_3_11', NULL, NULL, NULL),
  ('CD Leganés', 'cd-leganes', NULL, 3, 'ESP', 'manual_3_12', NULL, NULL, NULL),
  ('Mallorca', 'mallorca', NULL, 3, 'ESP', 'manual_3_13', NULL, NULL, NULL),
  ('Osasuna', 'osasuna', NULL, 3, 'ESP', 'manual_3_14', NULL, NULL, NULL),
  ('Rayo Vallecano', 'rayo-vallecano', NULL, 3, 'ESP', 'manual_3_15', NULL, NULL, NULL),
  ('Real Madrid', 'real-madrid', NULL, 3, 'ESP', 'manual_3_16', NULL, NULL, NULL),
  ('Real Sociedad', 'real-sociedad', NULL, 3, 'ESP', 'manual_3_17', NULL, NULL, NULL),
  ('Sevilla FC', 'sevilla-fc', NULL, 3, 'ESP', 'manual_3_18', NULL, NULL, NULL),
  ('Valencia CF', 'valencia-cf', NULL, 3, 'ESP', 'manual_3_19', NULL, NULL, NULL),
  ('Villarreal CF', 'villarreal-cf', NULL, 3, 'ESP', 'manual_3_20', NULL, NULL, NULL),
  ('Atalanta', 'atalanta', NULL, 4, 'ITA', 'manual_4_1', NULL, NULL, NULL),
  ('Bologna FC', 'bologna-fc', NULL, 4, 'ITA', 'manual_4_2', NULL, NULL, NULL),
  ('Cagliari', 'cagliari', NULL, 4, 'ITA', 'manual_4_3', NULL, NULL, NULL),
  ('Como 1907', 'como-1907', NULL, 4, 'ITA', 'manual_4_4', NULL, NULL, NULL),
  ('Empoli FC', 'empoli-fc', NULL, 4, 'ITA', 'manual_4_5', NULL, NULL, NULL),
  ('ACF Fiorentina', 'acf-fiorentina', NULL, 4, 'ITA', 'manual_4_6', NULL, NULL, NULL),
  ('Genoa CFC', 'genoa-cfc', NULL, 4, 'ITA', 'manual_4_7', NULL, NULL, NULL),
  ('Hellas Verona', 'hellas-verona', NULL, 4, 'ITA', 'manual_4_8', NULL, NULL, NULL),
  ('Inter Milan', 'inter-milan', NULL, 4, 'ITA', 'manual_4_9', NULL, NULL, NULL),
  ('Juventus', 'juventus', NULL, 4, 'ITA', 'manual_4_10', NULL, NULL, NULL),
  ('Lazio', 'lazio', NULL, 4, 'ITA', 'manual_4_11', NULL, NULL, NULL),
  ('Lecce', 'lecce', NULL, 4, 'ITA', 'manual_4_12', NULL, NULL, NULL),
  ('AC Milan', 'ac-milan', NULL, 4, 'ITA', 'manual_4_13', NULL, NULL, NULL),
  ('AC Monza', 'ac-monza', NULL, 4, 'ITA', 'manual_4_14', NULL, NULL, NULL),
  ('Napoli', 'napoli', NULL, 4, 'ITA', 'manual_4_15', NULL, NULL, NULL),
  ('Parma Calcio 1913', 'parma-calcio-1913', NULL, 4, 'ITA', 'manual_4_16', NULL, NULL, NULL),
  ('AS Roma', 'as-roma', NULL, 4, 'ITA', 'manual_4_17', NULL, NULL, NULL),
  ('Torino FC', 'torino-fc', NULL, 4, 'ITA', 'manual_4_18', NULL, NULL, NULL),
  ('Udinese', 'udinese', NULL, 4, 'ITA', 'manual_4_19', NULL, NULL, NULL),
  ('Venezia FC', 'venezia-fc', NULL, 4, 'ITA', 'manual_4_20', NULL, NULL, NULL),
  ('Angers SCO', 'angers-sco', NULL, 5, 'FRA', 'manual_5_1', NULL, NULL, NULL),
  ('AJ Auxerre', 'aj-auxerre', NULL, 5, 'FRA', 'manual_5_2', NULL, NULL, NULL),
  ('Stade Brestois 29', 'stade-brestois-29', NULL, 5, 'FRA', 'manual_5_3', NULL, NULL, NULL),
  ('Le Havre AC', 'le-havre-ac', NULL, 5, 'FRA', 'manual_5_4', NULL, NULL, NULL),
  ('RC Lens', 'rc-lens', NULL, 5, 'FRA', 'manual_5_5', NULL, NULL, NULL),
  ('Lille OSC', 'lille-osc', NULL, 5, 'FRA', 'manual_5_6', NULL, NULL, NULL),
  ('Olympique Lyonnais', 'olympique-lyonnais', NULL, 5, 'FRA', 'manual_5_7', NULL, NULL, NULL),
  ('Olympique de Marseille', 'olympique-de-marseille', NULL, 5, 'FRA', 'manual_5_8', NULL, NULL, NULL),
  ('AS Monaco', 'as-monaco', NULL, 5, 'FRA', 'manual_5_9', NULL, NULL, NULL),
  ('FC Nantes', 'fc-nantes', NULL, 5, 'FRA', 'manual_5_10', NULL, NULL, NULL),
  ('OGC Nice', 'ogc-nice', NULL, 5, 'FRA', 'manual_5_11', NULL, NULL, NULL),
  ('Paris Saint-Germain', 'paris-saint-germain', NULL, 5, 'FRA', 'manual_5_12', NULL, NULL, NULL),
  ('RC Racing Club de Strasbourg', 'rc-strasbourg', NULL, 5, 'FRA', 'manual_5_13', NULL, NULL, NULL),
  ('Stade Rennais FC', 'stade-rennais-fc', NULL, 5, 'FRA', 'manual_5_14', NULL, NULL, NULL),
  ('AS Saint-Étienne', 'as-saint-etienne', NULL, 5, 'FRA', 'manual_5_15', NULL, NULL, NULL),
  ('Toulouse FC', 'toulouse-fc', NULL, 5, 'FRA', 'manual_5_16', NULL, NULL, NULL),
  ('Montpellier HSC', 'montpellier-hsc', NULL, 5, 'FRA', 'manual_5_17', NULL, NULL, NULL),
  ('Stade de Reims', 'stade-de-reims', NULL, 5, 'FRA', 'manual_5_18', NULL, NULL, NULL)
ON CONFLICT (slug) DO UPDATE SET
  competition_id = EXCLUDED.competition_id,
  country_code = EXCLUDED.country_code,
  external_ref = EXCLUDED.external_ref,
  venue = EXCLUDED.venue,
  founded_year = EXCLUDED.founded_year,
  updated_at = NOW();

-- Verify import
-- SELECT c.name, COUNT(t.id) as team_count 
-- FROM competitions c
-- LEFT JOIN teams t ON c.id = t.competition_id
-- GROUP BY c.name
-- ORDER BY c.display_order;
